trailingComma: none
arrowParens: avoid
quoteProps: consistent
bracketSpacing: true
singleQuote: true
useTabs: false
semi: false
tabWidth: 4
printWidth: 80

overrides:
  - files: '*.{yml,yaml}'
    options:
      tabWidth: 2
